image:
  file: gitpod.Dockerfile
# Command to start on workspace startup
tasks:
  - command: >
      setup/wagtail.sh && python manage.py runserver 0.0.0.0:8000
    name: python
  - openMode: split-right
  - command: >
      setup/frontend.sh && cd frontend && sleep 5 && npm run gulp watch
    name: node
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
  - port: 3000
    onOpen: open-preview
